CREATE TABLE IF NOT EXISTS reservations (
    mes                                 VARCHAR(10),
    chegada                             DATE,
    data_de_checkout                    DATE,
    id_do_anuncio                       VARCHAR(50),
    nome_interno_do_anuncio             VARCHAR(100),
    reserva                             VARCHAR(50),
    nome_do_hospede                     VARCHAR(100),
    codigo_externo_de_reserva_ota       VARCHAR(50),
    canal                               VARCHAR(50),
    data_de_criacao                     DATE,
    data_do_repasse                     DATE,
    numero_de_noites                    INT,
    moeda                               VARCHAR(5),
    valor_por_noite                     DECIMAL(10, 2),
    total_da_reserva                    DECIMAL(10, 2),
    base_de_calculo_do_repasse          DECIMAL(10, 2),
    preco_de_venda_corrigido            DECIMAL(10, 2),
    comissao_da_empresa                 DECIMAL(10, 2),
    preco_de_compra                     DECIMAL(10, 2),
    total_da_fatura_de_hospedagem       DECIMAL(10, 2),
    total_de_servicos_extras            DECIMAL(10, 2),
    taxas_taxa_de_limpeza               DECIMAL(10, 2),
    taxa_do_proprietario_tp             DECIMAL(10, 2),
    primeiro_nome_do_hospede            VARCHAR(100),
    sobrenome_do_hospede                VARCHAR(100),
    status_da_reserva                   VARCHAR(50),
    agente                              VARCHAR(100)
);
